In [1]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
print(cancer.DESCR)

Breast Cancer Wisconsin (Diagnostic) Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, field
        13 is Radius SE, field 23 is Worst Radius.

        

In [2]:
X = cancer.data
y = cancer.target

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33)

In [4]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.94736842105263153

In [5]:
import numpy as np

y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [9]:
np.equal(y_pred, y_test).sum()

108

In [10]:
model.predict_proba(X_test)

array([[  9.99870086e-01,   1.29914017e-04],
       [  8.21078113e-03,   9.91789219e-01],
       [  4.44679091e-03,   9.95553209e-01],
       [  3.90436713e-02,   9.60956329e-01],
       [  2.02290224e-01,   7.97709776e-01],
       [  1.19411345e-01,   8.80588655e-01],
       [  3.56184777e-04,   9.99643815e-01],
       [  4.34084961e-04,   9.99565915e-01],
       [  3.07807183e-03,   9.96921928e-01],
       [  5.06056863e-03,   9.94939431e-01],
       [  1.89211609e-03,   9.98107884e-01],
       [  9.96615038e-01,   3.38496170e-03],
       [  2.63741456e-04,   9.99736259e-01],
       [  4.76529727e-01,   5.23470273e-01],
       [  1.22182602e-02,   9.87781740e-01],
       [  9.89551742e-01,   1.04482583e-02],
       [  4.15328877e-02,   9.58467112e-01],
       [  5.86926899e-03,   9.94130731e-01],
       [  8.29514594e-03,   9.91704854e-01],
       [  7.22185901e-02,   9.27781410e-01],
       [  8.18891404e-01,   1.81108596e-01],
       [  3.14610383e-04,   9.99685390e-01],
       [  

In [11]:
model2 = LogisticRegression(penalty='l1')
model2.fit(X_train, y_train)
model2.score(X_test, y_test)

0.95614035087719296

In [12]:
model2.intercept_

array([ 0.])

In [13]:
model2.coef_

array([[ 5.17288619,  0.07607999, -0.38748994, -0.01204708,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.29290214,  0.        , -0.03524823,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.31945715, -0.05263915, -0.02032057,  0.        ,
         0.        , -2.89441951,  0.        ,  0.        ,  0.        ]])